# Generated by Django 3.2 on 2021-04-09 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=31)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='contact_number', max_length=14)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'db_table': 'tbl_customers',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateTimeField(auto_now_add=True)),
                ('order_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('DLV', 'Delivered'), ('OFD', 'Out For Delivery')], max_length=3)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='orms.customer')),
            ],
            options={
                'verbose_name_plural': 'Order',
                'db_table': 'tbl_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=5)),
                ('payment_options', models.CharField(choices=[('COD', 'Cash On Delivery'), ('PYP', 'Paypal'), ('AP', 'Amazon Pay'), ('GP', 'Google Pay'), ('AE', 'American Express'), ('VSA', 'Visa Checkout'), ('MC', 'Master Card')], max_length=3)),
                ('other_details', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('address', models.CharField(max_length=31)),
                ('phone', models.CharField(help_text='contact number', max_length=14)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('fax', models.CharField(help_text='fax_number', max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('details', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'suppliers',
                'db_table': 'tbl_supplier',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('L', 'litre'), ('PCS', 'Pieces'), ('GM', 'Gram'), ('M', 'Metre')], max_length=3)),
                ('category', models.CharField(choices=[('ED', 'Electronic Devices'), ('EA', 'Electronic Accessories'), ('HB', 'Health & Beauty'), ('BT', 'Baby & Toys'), ('GP', 'Groceries & Pets'), ('MF', 'Men Fashion'), ('WF', 'Woman Fashion'), ('SO', 'Sport Outdoor')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orms.supplier')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'tbl_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orms.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='orms.product')),
            ],
            options={
                'verbose_name_plural': 'OrderDetail',
                'db_table': 'order_detail',
                'ordering': ['-created_at'],
            },
        ),
    ]
