# Generated by Django 3.2 on 2021-04-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='puskar', help_text='customer', max_length=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='contact_number', max_length=17),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='name', max_length=31),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(help_text='address', max_length=31),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='details',
            field=models.CharField(help_text='other details', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(help_text='email_address', max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='fax',
            field=models.CharField(help_text='fax number', max_length=14),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(help_text='supplier name', max_length=31),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(help_text='contact number', max_length=17),
        ),
    ]
