# Generated by Django 3.2 on 2021-04-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orms', '0002_auto_20210409_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='fax',
            field=models.CharField(help_text='fax number', max_length=17),
        ),
    ]
