# Generated by Django 3.2 on 2021-04-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orms', '0003_alter_supplier_fax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
