# Generated by Django 3.2 on 2021-04-09 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orms', '0005_payment_order_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orms.orderdetail'),
        ),
    ]
