# Generated by Django 3.2 on 2021-04-09 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orms', '0007_auto_20210409_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-bill_no'], 'verbose_name_plural': 'Payment'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order_detail',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='other_details',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='bill_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orms.payment'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('A', 'Available'), ('NA', 'Not Available')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orms.order'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orms.product'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bill_no',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_options',
            field=models.CharField(choices=[('CD', 'Cash on Delivery'), ('GP', 'Google Pay'), ('AP', 'Amazon Pay'), ('MC', 'Master Card'), ('VSA', 'Visa Checkout')], max_length=3),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payment_options',
        ),
    ]
